export enum EstadoEnvio {
  PENDIENTE = 'PENDIENTE',
  PROGRAMADO = 'PROGRAMADO',
  DESPACHADO = 'DESPACHADO',
  EN_TRANSITO = 'EN_TRANSITO',
  ENTREGADO = 'ENTREGADO',
  CANCELADO = 'CANCELADO',
  DEVUELTO = 'DEVUELTO',
}